#!/usr/bin/env python3
import pathlib

from strings_io import read_strings, write_strings

REPO_ROOT = pathlib.Path("/Users/shawn/Documents/Codex/vocaldive")
RESOURCE_ROOT = REPO_ROOT / "ios-app" / "VocalDiveCore" / "Sources" / "VocalDiveApp" / "Resources"
FALLBACK_COVERAGE_LANGUAGES = {"zh-Hans", "yue", "ar", "ru", "ko"}
FALLBACK_KEYS = {
    "omr.checklist.compare_source",
    "omr.checklist.correct_candidate",
    "omr.checklist.do_not_treat_as_final",
    "omr.provider.homr.best_for",
    "omr.provider.homr.license_note",
    "omr.provider.homr.summary",
    "omr.provider.oemer.best_for",
    "omr.provider.oemer.license_note",
    "omr.provider.oemer.summary",
    "omr.review.directions.note",
    "omr.review.layout.note",
    "omr.review.lyrics.note",
    "omr.review.measures.note",
    "omr.review.metadata.note",
    "omr.review.notes.note",
    "omr.review.parts.note",
    "omr.review.repeats.note",
    "omr.review.rests.note",
    "omr.stage.capture_or_import.note",
    "omr.stage.editable_musicxml_review.note",
    "omr.stage.full_page_element_capture.note",
    "omr.stage.image_preprocessing.note",
    "omr.stage.manual_correction.note",
    "omr.stage.musicxml_export.note",
    "omr.stage.omr_recognition.choose_provider",
    "omr.stage.omr_recognition.use_provider",
    "omr.stage.playback_validation.note",
    "omr.stage.scoredocument_import.note",
    "score.restore_previous_session",
    "settings.sync.description",
    "settings.sync.enable",
    "settings.sync.error_prefix",
    "settings.sync.first_run.message",
    "settings.sync.first_run.title",
    "settings.sync.last_synced_label",
    "settings.sync.not_now",
    "settings.sync.not_yet_synced",
    "settings.sync.section",
    "settings.sync.state.off",
    "settings.sync.state.on",
    "settings.sync.state.syncing",
    "settings.sync.state.unavailable",
    "settings.sync.toggle",
    "settings.sync.unavailable.cloudkit",
    "support.feedback.backend_not_configured",
    "support.feedback.details",
    "support.feedback.invalid_response",
    "support.feedback.network",
    "support.feedback.send",
    "support.feedback.sent",
    "support.feedback.server",
    "support.official_website",
    "text.language_usage_documentation_contact_and_feedback",
    "text.review_checklist",
    "text.summary",
    "text.v1_uses_placeholder_to_split_bilingual_text_into_phrase_units_english_keeps_word_level_cue_timing_inside_each_phrase_chinese_and_mixed_phrases_stay_phrase_based",
}

LANGUAGE_OVERRIDES: dict[str, dict[str, str]] = {
    "en": {
        "support.user_manual": "User Manual",
        "support.changelog": "Changelog",
        "text.contact": "Contact",
        "text.feel_free_to_contact_me": "Feel free to contact me",
        "text.new_features_fixes_and_known_issues": "New features, fixes, and known issues.",
        "text.daily_practice_trend_and_feature_time": "Daily practice trend and feature time",
        "text.feature_time": "Feature Time",
        "text.daily_trend": "Daily Trend",
        "text.usage_appears_after_you_switch_between_sections": "Usage appears after you switch between sections.",
        "score.import_score_file": "Import Score File",
        "text.load_demo": "Load Demo",
        "text.current_score": "Current score",
        "text.source": "Source",
        "text.provider": "Provider",
        "text.review_checklist": "Review checklist",
        "text.load_or_import_a_musicxml_score_first": "Load or import a MusicXML score first.",
        "text.load_or_import_a_musicxml_candidate_first": "Load or import a MusicXML candidate first.",
        "text.microphone_permission_is_required_for_live_pitch_tracking": "Microphone permission is required for live pitch tracking.",
        "text.loaded_demo_score_twinkle_excerpt": "Loaded demo score: Twinkle excerpt.",
        "text.added_rest": "Added rest.",
        "text.cleared_composition_draft": "Cleared composition draft.",
        "score.imported_placeholder": "Imported %@.",
        "text.added_placeholder": "Added %@.",
        "text.use_note_entry_to_create_the_first_musicxml_draft": "Use Note Entry to create the first MusicXML draft.",
        "text.create_a_simple_musicxml_score_then_load_it_into_practice": "Create a simple MusicXML score, then load it into practice.",
        "text.no_pitch": "No pitch",
        "text.unknown": "Unknown",
        "text.decimal2_beats": "%.2f beats",
        "support.feedback.privacy": "Feedback sends only the details you choose to include.",
        "support.feedback.cooldown": "Please wait a moment before sending another report.",
        "settings.sync.status_label": "Sync status",
        "settings.sync.unavailable.account": "Sign in to iCloud to enable sync.",
        "omr.provider.homr.summary": "Phone-photo-oriented OMR that can export MusicXML for review.",
        "omr.provider.homr.best_for": "Best for quick score photos and early MusicXML trials.",
        "omr.provider.homr.license_note": "Review the project and model licenses before bundling or redistribution.",
        "omr.provider.oemer.license_note": "Review model weights and upstream licenses before shipping.",
        "omr.stage.capture_or_import.note": "Capture or import PDF/image source material before recognition begins.",
        "omr.stage.image_preprocessing.note": "Deskew, normalize contrast, and clean the page before recognition.",
        "omr.stage.full_page_element_capture.note": "Capture notes, rests, lyrics, dynamics, repeats, and layout-critical markings.",
        "omr.stage.omr_recognition.use_provider": "Run the selected provider and import the generated MusicXML result.",
        "omr.stage.manual_correction.note": "Correct notes, lyrics, repeats, and layout details before practice.",
        "omr.stage.editable_musicxml_review.note": "Review the editable MusicXML candidate against the original score.",
        "omr.stage.playback_validation.note": "Validate playback order, pitches, and rhythms before training.",
        "omr.review.notes.note": "Check pitch, octave, rhythm, ties, and voice assignment.",
        "omr.review.directions.note": "Check tempo words, dynamics, rehearsal text, and expressive markings.",
        "omr.review.layout.note": "Check page and system layout against the source score.",
        "omr.checklist.correct_candidate": "Correct the MusicXML candidate before using it for practice.",
        "text.full_song_in_app_challenge_model_exists_os_level_alarm_behavior_depends_on_platform_apis": "Full-song in-app challenge model exists; OS-level alarm behavior depends on platform APIs.",
        "text.homr_oemer_audiveris_execution_still_runs_outside_the_apple_app_then_imports_musicxml": "homr/oemer/Audiveris execution still runs outside the Apple app, then imports MusicXML.",
        "text.v1_uses_placeholder_to_split_bilingual_text_into_phrase_units_english_keeps_word_level_cue_timing_inside_each_phrase_chinese_and_mixed_phrases_stay_phrase_based": "v1 uses %@ to split bilingual text into phrase units. English keeps word-level cue timing inside each phrase; Chinese and mixed phrases stay phrase-based.",
    },
    "zh-Hant": {
        "support.user_manual": "使用手冊",
        "support.changelog": "更新日誌",
        "text.contact": "聯絡方式",
        "text.feel_free_to_contact_me": "歡迎隨時聯絡我",
        "text.new_features_fixes_and_known_issues": "新功能、修正與已知事項。",
        "text.daily_practice_trend_and_feature_time": "每日練習趨勢與功能使用時間",
        "text.feature_time": "功能使用時間",
        "text.daily_trend": "每日趨勢",
        "text.usage_appears_after_you_switch_between_sections": "切換不同分頁後，這裡會開始顯示使用統計。",
        "score.import_score_file": "匯入樂譜檔案",
        "text.load_demo": "載入示範",
        "text.current_score": "目前樂譜",
        "text.source": "來源",
        "text.provider": "供應來源",
        "text.review_checklist": "校對清單",
        "text.load_or_import_a_musicxml_score_first": "請先載入或匯入 MusicXML 樂譜。",
        "text.load_or_import_a_musicxml_candidate_first": "請先載入或匯入 MusicXML 候選檔。",
        "text.microphone_permission_is_required_for_live_pitch_tracking": "即時音高追蹤需要麥克風權限。",
        "text.loaded_demo_score_twinkle_excerpt": "已載入示範樂譜：小星星節錄。",
        "text.added_rest": "已加入休止符。",
        "text.cleared_composition_draft": "已清除作曲草稿。",
        "score.imported_placeholder": "已匯入 %@。",
        "text.added_placeholder": "已加入 %@。",
        "text.use_note_entry_to_create_the_first_musicxml_draft": "使用音符輸入建立第一版 MusicXML 草稿。",
        "text.create_a_simple_musicxml_score_then_load_it_into_practice": "先建立簡單的 MusicXML 樂譜，再載入到練習模式。",
        "text.no_pitch": "未偵測到音高",
        "text.unknown": "未知",
        "text.decimal2_beats": "%.2f 拍",
        "support.feedback.privacy": "回饋只會送出你選擇填寫的內容。",
        "support.feedback.cooldown": "請稍候一下再送出下一則回饋。",
        "settings.sync.status_label": "同步狀態",
        "settings.sync.unavailable.account": "請先登入 iCloud 才能啟用同步。",
        "omr.provider.homr.summary": "適合手機拍照樂譜的 OMR，可輸出 MusicXML 供校對。",
        "omr.provider.homr.best_for": "適合快速拍照測試與早期 MusicXML 試作。",
        "omr.provider.homr.license_note": "打包或散布前請先確認專案與模型授權。",
        "omr.provider.oemer.license_note": "正式出貨前請先確認模型權重與上游授權。",
        "omr.stage.capture_or_import.note": "在辨識開始前先拍攝或匯入 PDF / 圖片來源。",
        "omr.stage.image_preprocessing.note": "辨識前先做去傾斜、對比標準化與頁面清理。",
        "omr.stage.full_page_element_capture.note": "擷取音符、休止符、歌詞、力度、反覆與影響版面的記號。",
        "omr.stage.omr_recognition.use_provider": "執行選定的辨識供應器，並匯入產生的 MusicXML。",
        "omr.stage.manual_correction.note": "在進入練習前修正音符、歌詞、反覆與版面細節。",
        "omr.stage.editable_musicxml_review.note": "將可編輯的 MusicXML 候選檔和原始樂譜逐項比對。",
        "omr.stage.playback_validation.note": "在訓練前先確認播放順序、音高與節奏。",
        "omr.review.notes.note": "檢查音高、八度、節奏、連音與聲部分配。",
        "omr.review.directions.note": "檢查速度文字、力度、排練記號與表情記號。",
        "omr.review.layout.note": "對照原始樂譜檢查頁面與系統版面。",
        "omr.checklist.correct_candidate": "請先修正 MusicXML 候選檔，再用於練習。",
        "text.full_song_in_app_challenge_model_exists_os_level_alarm_behavior_depends_on_platform_apis": "App 內完整歌曲挑戰模型已存在；系統層鬧鐘行為仍取決於平台 API。",
        "text.homr_oemer_audiveris_execution_still_runs_outside_the_apple_app_then_imports_musicxml": "homr / oemer / Audiveris 目前仍在 Apple App 外部執行，再把 MusicXML 匯回。",
        "text.v1_uses_placeholder_to_split_bilingual_text_into_phrase_units_english_keeps_word_level_cue_timing_inside_each_phrase_chinese_and_mixed_phrases_stay_phrase_based": "v1 會用 %@ 來切分中英雙語片語。英文會在各片語內保留單字層級節奏提示；中文與混合片語則維持片語層級。",
        "text.meter": "拍號",
        "practice.playback": "播放",
        "text.unmute": "取消靜音",
        "text.reference": "參考",
        "text.flat": "偏低",
        "practice.pitch_drill": "音高訓練",
        "text.target_2": "目標",
        "text.no_score_loaded": "尚未載入樂譜",
        "text.main_scan_workflow_pdf_image_score_musicxml_candidate_user_correction_annotations_playback_pitch_tracking_and_practice_history": "主掃描流程：PDF / 圖片樂譜 -> MusicXML 候選檔 -> 使用者校正 -> 註記、播放、音高追蹤與練習紀錄。",
        "text.highlighter": "螢光筆",
        "text.mic_idle": "麥克風待命中",
        "text.no_part_selected": "尚未選擇聲部",
        "text.untitled_vocaldive_score": "未命名聲海樂譜",
        "text.tempo": "速度",
        "score.musicxml_import": "MusicXML 匯入",
        "text.beat": "拍",
        "text.half": "二分音符",
        "text.clarity": "清晰度",
        "text.line_width": "線條粗細",
        "text.mute": "靜音",
        "practice.pitch_states": "音高狀態",
        "text.live_pitch_capture": "即時音高擷取",
        "text.share_midi": "分享 MIDI",
        "practice.pitch_overlay": "音高覆蓋",
        "text.mixer": "混音器",
        "text.confidence": "信心值",
        "text.red_mark_overlay": "紅色標記覆蓋",
        "text.current_passage": "目前段落",
        "text.no_notes_yet": "尚無音符",
        "practice.pitch_feedback": "音高回饋",
        "text.follow_score": "跟譜",
        "text.number_measures": "%d 小節",
        "practice.stop": "停止",
        "text.voice_practice": "聲音練習",
        "text.eighth": "八分音符",
        "text.fork": "音叉",
        "text.add_rest": "加入休止符",
        "practice.stop_metronome": "停止節拍器",
        "text.load_score": "載入樂譜",
        "text.voice": "聲部",
        "text.full_score_musicxml_review": "完整總譜 MusicXML 校對",
        "text.number_notes": "%d 音符",
        "practice.metronome": "節拍器",
        "text.sharp": "偏高",
        "text.quarter": "四分音符",
        "text.number_ticks": "%d tick",
        "text.hide_cues": "隱藏提示",
        "text.start_metronome": "開始節拍器",
        "practice.pitch_names": "音名",
        "text.target": "目標",
        "text.zoom": "縮放",
        "score.musicxml_preview": "MusicXML 預覽",
        "text.start": "開始",
        "practice.tuning_fork": "定音叉",
        "text.piano": "鋼琴",
        "annotation.annotations": "註記",
        "text.listening": "正在聆聽...",
        "text.measure_numbers": "小節編號",
        "text.live_pitch": "即時音高",
        "practice.play_selected_part": "播放所選聲部",
        "text.solo": "獨奏",
        "text.frequency": "頻率",
        "app.vocaldive_studio": "聲海工作室",
        "text.modes": "模式",
        "text.intonation_trace": "音準軌跡",
        "text.memory_cues": "記憶提示",
        "text.add_note": "加入音符",
        "practice.play": "播放",
        "text.clear": "清除",
        "practice.stop_playback": "停止播放",
        "text.octave_number": "第 %d 八度",
        "text.intonation": "音準",
        "text.note_entry": "音符輸入",
        "annotation.annotation_mode": "註記模式",
        "score.import_scores_practice_annotate_and_export": "匯入樂譜、練習、註記與匯出。",
        "nav.practice_display": "練習顯示",
        "nav.score_aligned_target_timeline": "與樂譜對齊的目標時間軸",
        "nav.score_mode": "樂譜模式",
        "practice.play_placeholder": "播放 %@。",
        "score.import_musicxml_pdf_or_score_images_musicxml_opens_directly_pdf_image_currently_enters_the_omr_intake_path_before_review": "匯入 MusicXML、PDF 或樂譜圖片。MusicXML 會直接開啟；PDF / 圖片目前會先進入 OMR 匯入流程等待校對。",
        "score.imported_placeholder_for_omr_intake_this_build_still_needs_an_external_omr_step_before_vocaldive_can_open_it_as_editable_musicxml": "已匯入 %@ 進入 OMR 流程。此版本仍需外部 OMR 步驟後，聲海才能以可編輯 MusicXML 開啟。",
        "score.imported_score": "已匯入樂譜",
        "score.musicxml_parsed": "MusicXML 解析完成",
        "text.build_queue": "建置佇列",
        "text.candidate_has_no_usable_notes": "候選檔沒有可用音符。",
        "text.candidate_has_score_data_review_correct_before_practice": "候選檔已含樂譜資料；請先校對修正再進入練習。",
        "text.correct_candidate_first_then_use_it_for_notes_annotations_playback_and_practice": "請先修正候選檔，再用於音符、註記、播放與練習。",
        "text.create_review_candidate": "建立校對候選檔",
        "text.editable_musicxml_correction_gate": "可編輯 MusicXML 校正關卡",
        "text.hidden": "已隱藏",
        "text.load_demo_score": "載入示範樂譜",
        "text.measure_placeholder": "小節 %@",
        "text.microphone_capture": "麥克風擷取",
        "text.no_score_loaded_2": "尚未載入樂譜",
        "text.number_vector_strokes_strokes_are_stored_as_scalable_paths_not_a_page_bitmap": "%d 筆向量筆畫。筆畫會以可縮放路徑保存，而不是頁面點陣圖。",
        "text.offline_pass": "離線練習",
        "text.omr_review": "OMR 校對",
        "text.pdf_image_import_is_accepted_but_in_app_omr_is_not_implemented_yet_convert_it_to_musicxml_first_then_import_the_musicxml_result": "目前接受 PDF / 圖片匯入，但 app 內 OMR 尚未完成。請先轉成 MusicXML，再匯入結果檔。",
        "text.placeholder_full_score_omr": "%@ 總譜 OMR",
        "text.ready_for_practice_after_review": "校對完成後即可進入練習",
        "text.real_microphone_pitch_tracking": "真實麥克風音高追蹤",
        "text.repeat_expansion_audit": "反覆展開校驗",
        "text.run_provider_import_generated_musicxml_then_validate_every_recognized_element": "執行供應器、匯入生成的 MusicXML，然後驗證每個辨識元素。",
        "text.this_file_type_is_not_supported_yet_import_musicxml_directly_or_use_pdf_image_for_the_omr_intake_path": "此檔案類型目前尚未支援。請直接匯入 MusicXML，或使用 PDF / 圖片走 OMR 流程。",
        "text.visible": "顯示中",
        "text.whole": "全音符",
        "text.yin_tracker_adapter": "YIN 追蹤器介面",
        "practice.stop_fork": "停止音叉",
        "text.alpha_0": "Alpha 0 版",
    },
    "zh-Hans": {
        "support.user_manual": "使用手册",
        "support.changelog": "更新日志",
        "text.contact": "联系方式",
        "text.feel_free_to_contact_me": "欢迎随时联系我",
        "text.no_pitch": "未检测到音高",
        "text.unknown": "未知",
        "text.decimal2_beats": "%.2f 拍",
        "text.review_checklist": "校对清单",
        "text.load_or_import_a_musicxml_score_first": "请先载入或导入 MusicXML 乐谱。",
        "text.load_or_import_a_musicxml_candidate_first": "请先载入或导入 MusicXML 候选文件。",
        "text.microphone_permission_is_required_for_live_pitch_tracking": "实时音高追踪需要麦克风权限。",
        "text.loaded_demo_score_twinkle_excerpt": "已载入示范乐谱：小星星节选。",
        "text.added_rest": "已加入休止符。",
        "text.cleared_composition_draft": "已清除作曲草稿。",
        "score.imported_placeholder": "已导入 %@。",
        "text.added_placeholder": "已加入 %@。",
        "text.use_note_entry_to_create_the_first_musicxml_draft": "使用音符输入建立第一版 MusicXML 草稿。",
        "text.create_a_simple_musicxml_score_then_load_it_into_practice": "先建立简单的 MusicXML 乐谱，再载入到练习模式。",
        "support.feedback.privacy": "反馈只会发送你选择填写的内容。",
        "support.feedback.cooldown": "请稍候再发送下一则反馈。",
        "settings.sync.status_label": "同步状态",
        "settings.sync.unavailable.account": "请先登录 iCloud 才能启用同步。",
    },
    "yue": {
        "support.user_manual": "使用手冊",
        "support.changelog": "更新日誌",
        "text.contact": "聯絡方式",
        "text.feel_free_to_contact_me": "歡迎隨時聯絡我",
        "text.no_pitch": "未偵測到音高",
        "text.unknown": "未知",
        "text.decimal2_beats": "%.2f 拍",
        "text.review_checklist": "校對清單",
        "support.feedback.privacy": "回饋只會送出你揀咗填寫嘅內容。",
        "support.feedback.cooldown": "請等一陣先再送出下一則回饋。",
        "settings.sync.status_label": "同步狀態",
        "settings.sync.unavailable.account": "請先登入 iCloud 先可以開啟同步。",
    },
    "es": {
        "support.user_manual": "Manual de uso",
        "support.changelog": "Registro de cambios",
        "text.contact": "Contacto",
        "text.feel_free_to_contact_me": "No dudes en contactarme",
        "text.no_pitch": "Sin tono",
        "text.unknown": "Desconocido",
        "text.decimal2_beats": "%.2f pulsos",
    },
    "ar": {
        "support.user_manual": "دليل الاستخدام",
        "support.changelog": "سجل التحديثات",
        "text.contact": "التواصل",
        "text.feel_free_to_contact_me": "لا تتردد في التواصل معي",
        "text.no_pitch": "لا توجد نغمة",
        "text.unknown": "غير معروف",
        "text.decimal2_beats": "%.2f نبضة",
        "support.feedback.privacy": "يُرسل التعليق فقط التفاصيل التي تختار تضمينها.",
        "support.feedback.cooldown": "يرجى الانتظار قليلًا قبل إرسال تقرير آخر.",
        "settings.sync.status_label": "حالة المزامنة",
        "settings.sync.unavailable.account": "سجّل الدخول إلى iCloud لتفعيل المزامنة.",
    },
    "ru": {
        "support.user_manual": "Руководство пользователя",
        "support.changelog": "Журнал изменений",
        "text.contact": "Контакты",
        "text.feel_free_to_contact_me": "Свяжитесь со мной в любое время",
        "text.no_pitch": "Нет высоты",
        "text.unknown": "Неизвестно",
        "text.decimal2_beats": "%.2f доли",
        "settings.sync.status_label": "Статус синхронизации",
        "settings.sync.unavailable.account": "Войдите в iCloud, чтобы включить синхронизацию.",
    },
    "pt": {
        "support.user_manual": "Manual do usuário",
        "support.changelog": "Registro de alterações",
        "text.contact": "Contato",
        "text.feel_free_to_contact_me": "Sinta-se à vontade para entrar em contato",
        "text.no_pitch": "Sem afinação",
        "text.unknown": "Desconhecido",
        "text.decimal2_beats": "%.2f batidas",
    },
    "id": {
        "support.user_manual": "Panduan pengguna",
        "support.changelog": "Catatan perubahan",
        "text.contact": "Kontak",
        "text.feel_free_to_contact_me": "Silakan hubungi saya kapan saja",
        "text.no_pitch": "Tidak ada nada",
        "text.unknown": "Tidak diketahui",
        "text.decimal2_beats": "%.2f ketukan",
    },
    "ja": {
        "support.user_manual": "ユーザーマニュアル",
        "support.changelog": "更新履歴",
        "text.contact": "連絡先",
        "text.feel_free_to_contact_me": "お気軽にご連絡ください",
        "text.new_features_fixes_and_known_issues": "新機能、修正、既知の事項。",
        "text.daily_practice_trend_and_feature_time": "日別練習傾向と機能利用時間",
        "text.feature_time": "機能利用時間",
        "text.daily_trend": "日別トレンド",
        "text.usage_appears_after_you_switch_between_sections": "セクションを切り替えると、ここに利用状況が表示されます。",
        "score.import_score_file": "譜面ファイルを読み込む",
        "text.load_demo": "デモを読み込む",
        "text.current_score": "現在の譜面",
        "text.source": "ソース",
        "text.provider": "プロバイダ",
        "text.review_checklist": "確認チェックリスト",
        "text.load_or_import_a_musicxml_score_first": "まず MusicXML 譜面を読み込むか取り込んでください。",
        "text.load_or_import_a_musicxml_candidate_first": "まず MusicXML 候補を読み込むか取り込んでください。",
        "text.microphone_permission_is_required_for_live_pitch_tracking": "ライブ音高追跡にはマイク権限が必要です。",
        "text.loaded_demo_score_twinkle_excerpt": "デモ譜面「きらきら星」抜粋を読み込みました。",
        "text.added_rest": "休符を追加しました。",
        "text.cleared_composition_draft": "作曲ドラフトを消去しました。",
        "score.imported_placeholder": "%@ を読み込みました。",
        "text.added_placeholder": "%@ を追加しました。",
        "text.use_note_entry_to_create_the_first_musicxml_draft": "音符入力で最初の MusicXML ドラフトを作成します。",
        "text.create_a_simple_musicxml_score_then_load_it_into_practice": "簡単な MusicXML 譜面を作成してから練習に読み込んでください。",
        "text.no_pitch": "音高なし",
        "text.unknown": "不明",
        "text.decimal2_beats": "%.2f 拍",
        "support.feedback.privacy": "フィードバックには、あなたが含めた内容だけが送信されます。",
        "support.feedback.cooldown": "次のレポートを送る前に少しお待ちください。",
        "settings.sync.status_label": "同期状態",
        "settings.sync.unavailable.account": "同期を有効にするには iCloud にサインインしてください。",
        "omr.provider.homr.summary": "スマホ撮影譜面向けの OMR で、確認用 MusicXML を出力できます。",
        "omr.provider.homr.best_for": "手早い譜面写真と初期 MusicXML 試作に最適です。",
        "omr.provider.homr.license_note": "同梱や再配布の前に、プロジェクトとモデルのライセンスを確認してください。",
        "omr.provider.oemer.license_note": "出荷前にモデル重みと上流ライセンスを確認してください。",
        "omr.stage.capture_or_import.note": "認識を始める前に PDF / 画像ソースを撮影または読み込みます。",
        "omr.stage.image_preprocessing.note": "認識前に傾き補正、コントラスト正規化、ページ清掃を行います。",
        "omr.stage.full_page_element_capture.note": "音符、休符、歌詞、強弱、反復、レイアウト重要記号を取り込みます。",
        "omr.stage.omr_recognition.use_provider": "選択したプロバイダを実行し、生成された MusicXML を読み込みます。",
        "omr.stage.manual_correction.note": "練習前に音符、歌詞、反復、レイアウト詳細を修正します。",
        "omr.stage.editable_musicxml_review.note": "編集可能な MusicXML 候補を原譜と照合します。",
        "omr.stage.playback_validation.note": "トレーニング前に再生順、音高、リズムを確認します。",
        "omr.review.notes.note": "音高、オクターブ、リズム、タイ、声部分配を確認します。",
        "omr.review.directions.note": "速度語、強弱、リハーサル記号、表情記号を確認します。",
        "omr.review.layout.note": "原譜と照らしてページとシステム配置を確認します。",
        "omr.checklist.correct_candidate": "練習に使う前に MusicXML 候補を修正してください。",
        "text.full_song_in_app_challenge_model_exists_os_level_alarm_behavior_depends_on_platform_apis": "アプリ内の全曲チャレンジモデルはありますが、OS レベルのアラーム動作はプラットフォーム API に依存します。",
        "text.homr_oemer_audiveris_execution_still_runs_outside_the_apple_app_then_imports_musicxml": "homr / oemer / Audiveris は現在も Apple App 外で実行し、その後 MusicXML を読み込みます。",
        "text.v1_uses_placeholder_to_split_bilingual_text_into_phrase_units_english_keeps_word_level_cue_timing_inside_each_phrase_chinese_and_mixed_phrases_stay_phrase_based": "v1 では %@ を使って日英混在テキストをフレーズ単位に分割します。英語は各フレーズ内で単語レベルのキュータイミングを維持し、中国語と混在フレーズはフレーズ単位のまま扱います。",
        "text.meter": "拍子",
        "practice.playback": "再生",
        "text.unmute": "ミュート解除",
        "text.reference": "参照",
        "text.flat": "低い",
        "practice.pitch_drill": "音高ドリル",
        "text.target_2": "目標",
        "text.no_score_loaded": "譜面が未読み込みです",
        "text.main_scan_workflow_pdf_image_score_musicxml_candidate_user_correction_annotations_playback_pitch_tracking_and_practice_history": "メイン走査フロー：PDF / 画像譜面 -> MusicXML 候補 -> ユーザー修正 -> 注記、再生、音高追跡、練習履歴。",
        "text.highlighter": "蛍光ペン",
        "text.mic_idle": "マイク待機中",
        "text.no_part_selected": "パート未選択",
        "text.untitled_vocaldive_score": "無題の VocalDive 譜面",
        "text.tempo": "テンポ",
        "score.musicxml_import": "MusicXML 読み込み",
        "text.beat": "拍",
        "text.half": "2分音符",
        "text.clarity": "明瞭さ",
        "text.line_width": "線の太さ",
        "text.mute": "ミュート",
        "practice.pitch_states": "音高状態",
        "text.live_pitch_capture": "ライブ音高取得",
        "text.share_midi": "MIDI を共有",
        "practice.pitch_overlay": "音高オーバーレイ",
        "text.mixer": "ミキサー",
        "text.confidence": "信頼度",
        "text.red_mark_overlay": "赤色マーク表示",
        "text.current_passage": "現在の区間",
        "text.no_notes_yet": "まだ音符がありません",
        "practice.pitch_feedback": "音高フィードバック",
        "text.follow_score": "譜面追従",
        "text.number_measures": "%d 小節",
        "practice.stop": "停止",
        "text.voice_practice": "発声練習",
        "text.eighth": "8分音符",
        "text.fork": "音叉",
        "text.add_rest": "休符を追加",
        "practice.stop_metronome": "メトロノーム停止",
        "text.load_score": "譜面を読み込む",
        "text.voice": "声部",
        "text.full_score_musicxml_review": "総譜 MusicXML 確認",
        "text.number_notes": "%d 音符",
        "practice.metronome": "メトロノーム",
        "text.sharp": "高い",
        "text.quarter": "4分音符",
        "text.number_ticks": "%d tick",
        "text.hide_cues": "キューを隠す",
        "text.start_metronome": "メトロノーム開始",
        "practice.pitch_names": "音名",
        "text.target": "目標",
        "text.zoom": "ズーム",
        "score.musicxml_preview": "MusicXML プレビュー",
        "text.start": "開始",
        "practice.tuning_fork": "調音叉",
        "text.piano": "ピアノ",
        "annotation.annotations": "注記",
        "text.listening": "聴取中...",
        "text.measure_numbers": "小節番号",
        "text.live_pitch": "ライブ音高",
        "practice.play_selected_part": "選択したパートを再生",
        "text.solo": "ソロ",
        "text.frequency": "周波数",
        "app.vocaldive_studio": "VocalDive Studio",
        "text.modes": "モード",
        "text.intonation_trace": "音程トレース",
        "text.memory_cues": "記憶キュー",
        "text.add_note": "音符を追加",
        "practice.play": "再生",
        "text.clear": "クリア",
        "practice.stop_playback": "再生停止",
        "text.octave_number": "オクターブ %d",
        "text.intonation": "音程",
        "text.note_entry": "音符入力",
        "annotation.annotation_mode": "注記モード",
        "support.official_website": "公式サイト",
        "text.choose_the_interface_language_the_change_applies_immediately_across_the_app": "表示言語を選択します。変更はアプリ全体にすぐ反映されます。",
        "text.language_usage_documentation_contact_and_feedback": "言語、利用状況、ドキュメント、連絡先、フィードバック",
        "score.restore_previous_session": "前回のセッションを復元",
        "support.feedback.backend_not_configured": "フィードバック送信先がまだ設定されていません。",
        "omr.checklist.compare_source": "原譜と一つずつ見比べて確認します。",
        "omr.review.metadata.note": "タイトル、作曲者、作詞者、編曲者、著作権表記を確認します。",
        "app.vocaldive_studio": "VocalDive スタジオ",
        "nav.experimental_sing_to_dismiss_alarm": "実験機能：歌って停止するアラーム",
        "nav.experimental_text_rhythm_speech_lab": "実験機能：テキストリズム発話ラボ",
        "nav.practice_display": "練習表示",
        "nav.practice_metrics": "練習指標",
        "nav.score_aligned_target_timeline": "譜面同期ターゲットタイムライン",
        "nav.score_mode": "譜面モード",
        "nav.score_sequence": "譜面シーケンス",
        "nav.score_settings": "譜面設定",
        "nav.scoredocument_wrapper": "ScoreDocument ラッパー",
        "practice.pitch": "音高",
        "practice.pitch_target": "目標音高",
        "practice.play_placeholder": "%@ を再生",
        "practice.playable_notes": "再生可能音符",
        "practice.playback_finished": "再生が完了しました。",
        "practice.playback_stopped": "再生を停止しました。",
        "practice.playing_placeholder": "%@ を再生中。",
        "practice.stop_fork": "音叉を停止",
        "score.export_musicxml": "MusicXML を書き出す",
        "score.exported_midi_for_placeholder": "%@ の MIDI を書き出しました。",
        "score.exported_musicxml_placeholder": "MusicXML を書き出しました：%@。",
        "score.import_musicxml_pdf_or_score_images_musicxml_opens_directly_pdf_image_currently_enters_the_omr_intake_path_before_review": "MusicXML、PDF、または譜面画像を読み込みます。MusicXML は直接開き、PDF / 画像は確認前の OMR 取り込み経路に入ります。",
        "score.import_scores_practice_annotate_and_export": "譜面を読み込み、練習し、注記し、書き出します。",
        "score.imported_placeholder_for_omr_intake_this_build_still_needs_an_external_omr_step_before_vocaldive_can_open_it_as_editable_musicxml": "%@ を OMR 取り込み用に読み込みました。このビルドでは、VocalDive が編集可能な MusicXML として開く前に外部 OMR ステップが必要です。",
        "score.imported_score": "読み込み済み譜面",
        "score.musicxml_composer": "MusicXML 作成",
        "score.musicxml_parsed": "MusicXML 解析済み",
        "text.accidental": "臨時記号",
        "text.active": "稼働中",
        "text.beat_type": "拍の種類",
        "text.beats": "拍数",
        "text.bug": "不具合",
        "text.build_queue": "処理キュー",
        "text.candidate_has_no_usable_notes": "候補には使用可能な音符がありません。",
        "text.candidate_has_score_data_review_correct_before_practice": "候補には譜面データがあります。練習前に確認・修正してください。",
        "text.category": "カテゴリ",
        "text.completion": "完了度",
        "text.confidence_decimal2": "信頼度 %.2f",
        "text.low_confidence": "低信頼度",
        "text.prototype_flow": "試作フロー",
        "text.platform_boundary": "プラットフォーム境界",
        "text.omr_review": "OMR 確認",
        "text.measures": "小節",
        "text.pen": "ペン",
        "text.wake_time": "起床時刻",
        "text.microphone_capture": "マイク入力",
        "text.cue_span_number_number": "キュー範囲：%d-%d",
        "text.sessions": "セッション数",
        "text.decimal1_cents_confidence_decimal2": "%.1f セント、信頼度 %.2f",
        "text.duration": "長さ",
        "text.accidental": "臨時記号",
        "text.completion": "完了度",
        "text.paragraph_rhythm_guide_and_speech_practice_scoring_model_exists": "段落リズムガイドと発話練習スコアモデルはすでに存在します。",
        "text.undo": "取り消す",
        "text.sharp_2": "シャープ",
        "text.flat_2": "フラット",
        "text.open_score": "譜面を開く",
        "text.guide": "ガイド",
        "text.share_musicxml": "MusicXML を共有",
        "text.removed_last_composed_event": "最後に追加したイベントを削除しました。",
        "text.rhythm": "リズム",
        "text.eraser": "消しゴム",
        "text.total_time": "合計時間",
        "text.in_tune": "音程一致",
        "text.external_omr_engine_execution": "外部 OMR エンジン実行",
        "text.demo_song": "デモ曲",
        "text.offline_pass": "オフライン練習",
        "text.whole": "全音符",
        "text.midi_playback_export": "MIDI 再生 / 書き出し",
        "text.segmentation": "分割方法",
        "text.category": "カテゴリ",
        "text.core_deviation_model_exists_live_tracker_is_next": "偏差モデルの基盤はできており、次はライブ追跡です。",
        "text.part_name": "パート名",
        "text.phrases": "フレーズ数",
        "text.natural": "ナチュラル",
        "text.usability": "使いやすさ",
        "text.none": "なし",
        "text.rate": "速度",
        "text.coverage": "達成率",
        "text.language": "言語",
        "text.phrase_match": "フレーズ一致度",
        "text.timeline": "タイムライン",
        "text.midi_event_timeline": "MIDI イベントタイムライン",
        "text.editable_musicxml_correction_gate": "編集可能 MusicXML 修正ゲート",
        "text.events": "イベント",
        "text.english_only_sessions_can_also_report_words_min_placeholder": "英語のみのセッションでは、%@ 語 / 分も表示できます。",
        "text.repeat_expansion_audit": "反復展開監査",
        "text.correct_candidate_first_then_use_it_for_notes_annotations_playback_and_practice": "まず候補を修正してから、音符、注記、再生、練習に使ってください。",
        "text.value": "値",
        "text.pdf_image_editable_musicxml_review": "PDF / 画像 -> 編集可能 MusicXML 確認",
        "text.measure_placeholder": "小節 %@",
        "text.run_provider_import_generated_musicxml_then_validate_every_recognized_element": "プロバイダを実行し、生成された MusicXML を読み込んでから、認識された要素を検証します。",
        "text.hidden": "非表示",
        "text.missing_target": "目標なし",
        "text.note": "音符",
        "text.type": "種類",
        "text.feature": "機能",
        "text.how_dismissal_works": "解除の仕組み",
        "text.phrases_min": "フレーズ / 分",
        "text.on": "オン",
        "text.off": "オフ",
        "text.title": "タイトル",
        "text.parts": "パート",
        "text.rest": "休符",
        "text.visible": "表示中",
        "text.sample_prompt": "サンプル文",
        "text.yin_tracker_adapter": "YIN トラッカーアダプタ",
        "text.real_microphone_pitch_tracking": "実マイク音高追跡",
        "text.created_number_notes_from_compose": "Compose から %d 個の音符を作成しました。",
        "text.created_editable_musicxml_review_candidate": "編集可能 MusicXML の確認候補を作成しました。",
        "text.this_file_type_is_not_supported_yet_import_musicxml_directly_or_use_pdf_image_for_the_omr_intake_path": "このファイル形式はまだ未対応です。MusicXML を直接読み込むか、PDF / 画像を OMR 取り込み経路で使用してください。",
        "text.pdf_image_import_is_accepted_but_in_app_omr_is_not_implemented_yet_convert_it_to_musicxml_first_then_import_the_musicxml_result": "PDF / 画像の読み込みは可能ですが、アプリ内 OMR はまだ未実装です。先に MusicXML に変換してから結果を読み込んでください。",
        "text.no_score_loaded_2": "譜面が未読み込みです",
        "text.main_workflow_gate_check_scanned_notes_lyrics_directions_repeats_and_layout_before_practice": "主な確認ゲート：練習前に、読み取った音符、歌詞、指示、反復、レイアウトを確認します。",
        "text.selected_part": "選択中のパート",
        "text.scan_correct_and_practice_from_editable_musicxml": "編集可能な MusicXML から読み取り、修正し、練習する",
        "text.ready_for_practice_after_review": "確認後は練習を開始できます",
        "text.placeholder_full_score_omr": "%@ 総譜 OMR",
        "text.number_vector_strokes_strokes_are_stored_as_scalable_paths_not_a_page_bitmap": "%d 本のベクターストローク。ストロークはページのビットマップではなく、拡大可能なパスとして保存されます。",
        "text.create_review_candidate": "確認候補を作成",
        "text.alpha_0": "Alpha 0 版",
    },
    "ko": {
        "support.user_manual": "사용 설명서",
        "support.changelog": "업데이트 기록",
        "text.contact": "연락처",
        "text.feel_free_to_contact_me": "편하게 연락해 주세요",
        "text.no_pitch": "음정 없음",
        "text.unknown": "알 수 없음",
        "text.decimal2_beats": "%.2f 박",
        "settings.sync.unavailable.account": "동기화를 켜려면 iCloud에 로그인하세요.",
    },
    "th": {
        "support.user_manual": "คู่มือผู้ใช้",
        "support.changelog": "บันทึกการอัปเดต",
        "text.contact": "ติดต่อ",
        "text.feel_free_to_contact_me": "ติดต่อฉันได้เสมอ",
        "text.no_pitch": "ไม่พบระดับเสียง",
        "text.unknown": "ไม่ทราบ",
        "text.decimal2_beats": "%.2f จังหวะ",
    },
    "it": {
        "support.user_manual": "Manuale utente",
        "support.changelog": "Registro aggiornamenti",
        "text.contact": "Contatti",
        "text.feel_free_to_contact_me": "Sentiti libero di contattarmi",
        "text.no_pitch": "Nessuna altezza",
        "text.unknown": "Sconosciuto",
        "text.decimal2_beats": "%.2f battiti",
    },
    "de": {
        "support.user_manual": "Benutzerhandbuch",
        "support.changelog": "Änderungsprotokoll",
        "text.contact": "Kontakt",
        "text.feel_free_to_contact_me": "Du kannst mich jederzeit kontaktieren",
        "text.no_pitch": "Kein Ton",
        "text.unknown": "Unbekannt",
        "text.decimal2_beats": "%.2f Schläge",
    },
}


def main() -> int:
    english_values = read_strings(RESOURCE_ROOT / "en.lproj" / "Localizable.strings")
    for language, overrides in LANGUAGE_OVERRIDES.items():
        path = RESOURCE_ROOT / f"{language}.lproj" / "Localizable.strings"
        values = read_strings(path)
        values.update(overrides)
        if language in FALLBACK_COVERAGE_LANGUAGES:
            for key in FALLBACK_KEYS:
                values.setdefault(key, english_values.get(key, key))
        write_strings(path, values)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
